name: Check formatting
on: [push, pull_request]

jobs:
  build-linux-gcc:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v1
      - name: install 3rd party dependencies
        run: |
          sudo apt-get update
          sudo apt-get install astyle
      - name: verify formatting
        run: |
          cd bm
          cc -o nobuild nobuild.c
          ./nobuild fmt
          git diff --exit-code
